# Generated by Django 4.0.4 on 2022-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(max_length=155, null=True, verbose_name='Job title'),
        ),
    ]
